In [1]:
import stadata

In [3]:
import stadata

# Replace 'token' with your actual API token obtained from WebAPI BPS - https://webapi.bps.go.id/developer/
client = stadata.Client('1a27be6154a2a74e1a857a317a0cc24c')

In [11]:
client.list_domain()

    domain_id   domain_name                        domain_url           level
0        0000         Pusat              http://www.bps.go.id        nasional
1        1100          Aceh            https://aceh.bps.go.id        provinsi
2        1101      Simeulue     https://simeuluekab.bps.go.id  kota/kabupaten
3        1102  Aceh Singkil  https://acehsingkilkab.bps.go.id  kota/kabupaten
4        1103  Aceh Selatan  https://acehselatankab.bps.go.id  kota/kabupaten
..        ...           ...                               ...             ...
544      9433        Puncak       https://puncakkab.bps.go.id  kota/kabupaten
545      9434       Dogiyai      https://dogiyaikab.bps.go.id  kota/kabupaten
546      9435    Intan Jaya    https://intanjayakab.bps.go.id  kota/kabupaten
547      9436        Deiyai       https://deiyaikab.bps.go.id  kota/kabupaten
548      9471      Jayapura    https://jayapurakota.bps.go.id  kota/kabupaten

[549 rows x 4 columns]

In [16]:
client.list_publication(all=False, domain=['3101'], year="2022")

,title,issn,sch_date,rl_date,updt_date,size,domain
pub_id,,,,,,,
ea2970f02fddf614173d0346,Produk Domestik Regional Bruto Kabupaten Admin...,-,2023-04-28,2023-04-28,NaN,2.33 MB,3101
178cf0276cf72ba13d8a1f59,Produk Domestik Regional Bruto kabupaten Admin...,-,2023-04-05,2023-04-05,NaN,5.83 MB,3101
266ee450805e3fa67ad7a3cd,Kabupaten Kepulauan Seribu Dalam Angka 2023,1978-9203,2023-02-28,2023-02-28,NaN,6.95 MB,3101
0886ee014a30232384830f83,Hasil Long Form Sensus Penduduk 2020 Kabupaten...,-,NaN,2023-02-09,NaN,3.64 MB,3101
bd33f67a83e626c65b6d08ec,Statistik Daerah Kepulauan Seribu 2022,2087-6246,NaN,2022-12-29,NaN,5.17 MB,3101
...,...,...,...,...,...,...,...
fe3cbef89f881f622a1bfe06,Kecamatan Kepulauan Seribu Selatan Dalam Angka...,NaN,2011-08-15,2011-08-15,NaN,MB,3101
7e196fac9910bf80b22f3231,Kecamatan Kepulauan Seribu Selatan Dalam Angka...,NaN,2011-06-24,2011-06-24,NaN,MB,3101
60ff36f6f2f619382c94a4fe,Statistik Daerah Kabupaten Kepulauan Seribu 2010,NaN,2011-06-24,2011-06-24,NaN,MB,3101
41484033130556bd53aa1b85,Kecamatan Kepulauan Seribu Utara Dalam Angka 2009,NaN,2011-06-24,2011-06-24,NaN,MB,3101
2755a0aa0f19d1a448cbc190,KABUPATEN KEPULAUAN SERIBU DALAM ANGKA TAHUN 2010,NaN,2011-01-21,2011-01-21,NaN,MB,3101

In [18]:
client.view_publication(domain='3101', idx='266ee450805e3fa67ad7a3cd')

TypeError: Client.view_publication() got an unexpected keyword argument 'idx'